#!/bin/bash

#set -x
set -e

GENTOO_REPO="${GENTOO_REPO:-/var/db/repos/gentoo}"
GKEYWORD="${GKEYWORD:-~riscv}"
export NAMEVERSION="<category>/<name>/<name>-<version>.ebuild"

ACCEPT_KEYWORDS="~*" emerge --autounmask y --autounmask-continue y $@

while :; do
    emerge --pretend --empty $@ 2>&1 \
        | grep 'masked by: missing keyword' \
        | head -n 1 \
        | awk '{print $2}' \
        | xargs -i qatom -F "%{CATEGORY}/%{PN}" {} \
        | xargs -i eix -I --format '<installedversions:NAMEVERSION>' {} \
        | xargs -t -i ekeyword ${GKEYWORD} ${GENTOO_REPO}/{}

    echo "${PIPESTATUS[@]}"
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        break
    fi
done

git -C "${GENTOO_REPO}" status \
    | grep -E 'modified:.*\/.*\/.*\.ebuild$' \
    | tr -s ' ' \
    | cut -d' ' -f 2 \
    | xargs dirname \
    | sort | uniq \
    | xargs -i bash -c "echo try to commit {} && cd $GENTOO_REPO/{} && repoman full -dx -j $(nproc) && repoman commit -m \"{}: keyword ~riscv\""
