#!/bin/bash

set -x

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# https://github.com/toralf/tinderbox/blob/master/bin/bwrap.sh

function gwrap() {
    local rootfs=(${1})
    [ -z "$rootfs" ] && echo "$rootfs is empty"

    local append=(${2})
    [ -z "$append" ] && append=(/bin/bash -l)

    local hostname="${HOMENAME:-test}"

    local sandbox=(env -i
        #PATH=/usr/sbin:/usr/bin:/sbin:/bin
        HOME=/root
        SHELL=/bin/bash
        TERM=linux
        /usr/bin/bwrap
            #--unshare-user
            #--unshare-net
            --unshare-cgroup
            --unshare-ipc
            --unshare-pid
            --unshare-uts
            --hostname $hostname
            --die-with-parent
            --setenv https_proxy "${https_proxy}"
            --setenv http_proxy "${http_proxy}"
            ${rootfs[@]}
            --dev                           /dev
            --perms 1777 --tmpfs            /dev/shm
            --proc                          /proc
            --tmpfs                         /run
            --ro-bind   /sys                /sys
            --perms 1777 --tmpfs            /tmp
            --bind  /var/cache/distfiles    /var/cache/distfiles
            --perms 1777 --tmpfs            /var/tmp/portage
            --bind  "$SCRIPT_DIR/gentoo"    /var/db/repos/gentoo
            ${append[@]}
    )

    ("${sandbox[@]}")
    local rc=$?
    return $rc
}

#bwrap_rootfs="
#    --bind /usr     /usr
#    --bind /bin     /bin
#    --bind /lib64   /lib64
#"
##gwrap "$bwrap_rootfs" "/bin/bash -l"

#SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#gwrap "--bind $SCRIPT_DIR/images/amd64-systemd-stable /" "${@}"

gwrap "--bind $1 /" "${2}"

